version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: OUKtFU8CjEaiF4+4KAxEnMPWng0zMmT0Ymcn140iJVV7MmkSGzUhWy8JAJ6/3RlC
  artifact: /.*\.nupkg/